# Generated by Django 4.2.6 on 2023-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("NB", "Non-binary"),
                            ("X", "Unknown"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField(max_length=200)),
                ("history", models.CharField(max_length=200)),
                ("occupation", models.CharField(max_length=200)),
                ("medication", models.CharField(max_length=200)),
            ],
        ),
    ]
